// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7vY-aV26rlkSaH47sIA6BXXAqUlLs74',
    appId: '1:895467730252:web:802b7cc47608b21cb08be9',
    messagingSenderId: '895467730252',
    projectId: 'laams-workspace-dev',
    authDomain: 'laams-workspace-dev.firebaseapp.com',
    databaseURL:
        'https://laams-workspace-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laams-workspace-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHuGKYriMOXDvHa5pxLuYs-4y0YdijzE',
    appId: '1:895467730252:android:62abffa5359bc2a9b08be9',
    messagingSenderId: '895467730252',
    projectId: 'laams-workspace-dev',
    databaseURL:
        'https://laams-workspace-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laams-workspace-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBci890mwnfWes93qMkxtPex_kgA0Ubd88',
    appId: '1:895467730252:ios:8e9be202f8c5b24db08be9',
    messagingSenderId: '895467730252',
    projectId: 'laams-workspace-dev',
    databaseURL:
        'https://laams-workspace-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laams-workspace-dev.appspot.com',
    iosClientId:
        '895467730252-lvcnddrr7vmcbrses7njrfvor34s0e84.apps.googleusercontent.com',
    iosBundleId: 'com.laams.converseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBci890mwnfWes93qMkxtPex_kgA0Ubd88',
    appId: '1:895467730252:ios:e70b559a15b179b8b08be9',
    messagingSenderId: '895467730252',
    projectId: 'laams-workspace-dev',
    databaseURL:
        'https://laams-workspace-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laams-workspace-dev.appspot.com',
    iosClientId:
        '895467730252-u6o13o1j5lsk12f0pbiie7ind6rjdgut.apps.googleusercontent.com',
    iosBundleId: 'com.laams.converseExample.RunnerTests',
  );
}
